development:
  adapter: postgresql
  encoding: utf8
  database: z.conference_development
  pool: 5
  username: z.conference
  password: 123123

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: db.polad.ru

