# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d07f9ed41f350f04bbfe3a40346fb83ffbf442a9270e6deeee16bb0d3a39b21ed2514cdb7c50c79fe64f9e77454ebd8d1d6f91b018aa30c7073bd5b4e63c280

test:
  secret_key_base: 519fb97f0e2b8b5f85543ed873291a094dd2fe7dfd228cdc77bcc31abe05b7d4dfcd78d96fe61b3a20582924f54c0d7f67e4837c944d5ea2a28791f369f3bbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
